### ISSUE TITLE
[BUG] Requirements.txt requests non-existent pytorch==1.10.0

### ISSUE THREAD

**Issue by epiphyte** [tyronechen/ziran#2]
**Describe the bug**
When trying to install the dependencies it fails with pytorch 1.10 not available.

**To Reproduce**
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt

**Expected behavior**
In installs with no issue

**Suggested fix**
pytorch was renamed torch. Replace pytorch with torch.

**Comment by tyronechen** [comment]
Dear @epiphyte , thanks for letting us know.

I tested this on `pip` and it looks like that pytorch distribution is not available there. However, installation through `mamba` works as it is available on anaconda.

I updated the install instructions in the README and documentation to reflect this, [and added a link to mamba's install](https://mamba.readthedocs.io/en/latest/installation.html).

Once `mamba` is installed, `mamba install -c tyronechen -c conda-forge genomenlp` should work correctly.
